services:
  - type: web
    name: ai-grading-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_grading_ui.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false 